/***
Abbreviate
Write a program (Abbreviate) that reads a full name consisting of a first name,
 a middle name, and a last name, and returns a well-formatted full name with an
  abbreviated middle name. Here are two run-time examples:
      Enter a name: John Quincy Adams
      John Q. Adams
      Enter a name: tommy lee Jones
      Tommy L. Jones
(As usual, the user's input is underlined; everything else is generated by the program).
Note that the program performs two services. First, it replaces the middle name with its
 first letter, follows by a period. Second, the program capitalizes the first character
  of each one of the three name-parts.
***/

import java.util.Scanner;
public class Abbreviate {

	public static void main(String[] args) {
		Scanner s = new Scanner(System.in); 
		System.out.print("Please enter your name: ");
		String name = s.nextLine();
		
		Scanner scan = new Scanner(name);
		String firstName = scan.next();
		//System.out.println(firstName);
		String middleName = scan.next();
		//System.out.println(middleName);
		String lastName = scan.next();
		//System.out.println(lastName);
		
		String firstLetter = firstName.substring(0,1).toUpperCase();
		String middleNameAbbreviate = middleName.substring(0,1).toUpperCase();
		String lastLetter = lastName.substring(0,1).toUpperCase();
		System.out.println(firstLetter + firstName.substring(1) + " " + middleNameAbbreviate + ". " +  lastLetter + lastName.substring(1));
		s.close();		
		scan.close();
				
	}

}
